# empty password should not exist in the config file
instance_testbench:
  global:
    # common parameters
    home_path: ~/scheduler
    log_level: INFO
    time: 1
  statistics:
    # for statistics collector
    capacity: 500
    minimum: 10
    maximum: 80
    threads: 1
    tasks: 99999
  connection:
    # for connection parameters
    host: 127.0.0.1
    port: 28801
    user: root
    # password:  
    database: test
    table: testbench
  dataset:
    # for dataset parameteres
    partitions: 9
    rows: 1000000
  distributed:
    threads: 10
    tasks: 99999
    participants: 1
    operations: 10
